#!/usr/bin/perl

# Copyright 2021 Hypernova Oy
# Copyright 2016 Vaara-kirjastot
#

use Modern::Perl;
use Carp;
use Getopt::Long qw(:config no_ignore_case);

use RTTTL::Daemon;
use RTTTL::Player;

my %params = ();

GetOptions(
#OPERATIONS
    'h|help'                      => \$params{help},
    'daemon'                      => \$params{daemon},
    'l|list'                      => \$params{list},
    's|song:s'                    => \$params{song},
    'R|random'                    => \$params{random},
    'r|rtttl:s'                   => \$params{rtttl},
#SELECTORS
    'S|selector:s'                => \$params{selector},
    'i|index:i'                   => \$params{idx},
#PARAMETERS
    'd|dir:s'                     => \$params{dir},
    'p|pin:i'                     => \$params{pin},
    'v|verbose:i'                 => \$params{cverbose},
    'rundir:s'                    => \$params{rundir},
    'user:s'                      => \$params{user},
    'group:s'                     => \$params{group},
);

my $usage = <<USAGE;


A happy RTTTL-player to play RTTTL-songs from the given directory
You can configure some of these options in /etc/emb-rtttl/config

OPERATIONS:

  -h --help               HELP!

  --daemon                Starts a daemon process listening at /run/emb-rtttl/sock

  -l --list               list all songs

  -s --song               play the target song

  -R --random             play a random song

  -r --rtttl              rtttl-song/codes to play, eg.
                          ToveriAccessDenied:d=4,o=4,b=100:32e,32d,32e,4c

SELECTORS:

  -S --selector           Select all song names matching this regexp. Defaults to all songs.

  -i --index              From the selected songs, pick this index. Starts from 0.

PARAMETERS:

  -d --dir                Which directory to use as the song base?

  -p --pin                Which GPIO pin to use for playback?

  -v --verbose            Defaults to 0, minimal output.
                          1, some output

  --rundir PATH           Where the daemon socket and pid are placed, defaults to ./

  --user NAME             Defaults to pi
  --group NAME            Defaults to gpio

EXAMPLES:

  perl scripts/rtttl-player -p 1 -d rtttl --list
  perl scripts/rtttl-player -p 1 -d rtttl --song nyancat
  rtttl-player -p 1 --random
  rtttl-player --daemon
  rtttl-player --selector '^Abba' --random
  rtttl-player --selector '^Abba' --index 1

USAGE

if ($params{help}) {
  print $usage;
  exit 0;
}

my $player = RTTTL::Player->new(\%params);

if (defined($params{daemon})) {
  RTTTL::Daemon::start_daemon($player);
}
else {
  $player->dispatchOperation();
}

